// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBySA8UfVf-apzU18p1AoNgsIbeTjbGsdQ',
    appId: '1:19202076505:web:854bc4dba41aa0be262648',
    messagingSenderId: '19202076505',
    projectId: 'budgetcontroller-6094c',
    authDomain: 'budgetcontroller-6094c.firebaseapp.com',
    storageBucket: 'budgetcontroller-6094c.appspot.com',
    measurementId: 'G-P0KSYSJH85',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCq0cdoEyTE_AqiJzDuzHw56oFxgQoqXA',
    appId: '1:19202076505:ios:3f02f0f298dfde61262648',
    messagingSenderId: '19202076505',
    projectId: 'budgetcontroller-6094c',
    storageBucket: 'budgetcontroller-6094c.appspot.com',
    iosClientId: '19202076505-0buuib6aal3r1nv9beqfevak9qnht4ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetController',
  );
}
